# Generated by Django 5.2.6 on 2025-09-14 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afpsn', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, choices=[('OFFICER', 'Officer'), ('ENLISTED', 'Enlisted Personnel'), ('CIVILIAN', 'Civilian'), ('OTHERS', 'Others')], max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_initial', models.CharField(blank=True, max_length=10, null=True)),
                ('extension_name', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('default_avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_password_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('password_reset_expiration', models.DateTimeField(blank=True, null=True)),
                ('display_name_format', models.CharField(choices=[('title', 'Title Case (John De La Cruz)'), ('camel', 'Upper Camel Case (JohnDeLaCruz)'), ('upper', 'UPPERCASE (JOHN DE LA CRUZ)'), ('lower', 'lowercase (john de la cruz)')], default='title', help_text="Controls how the user's display name is formatted", max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
